### ISSUE TITLE
about requirements.txt carla==0.9.7 

### ISSUE THREAD

**Issue by ScienceZhi** [littlemountainman/modeld#12]
hi, Author.
carla==0.9.7 how to get?

When I carry out orders( pip3 install -r requirements.txt )

ERROR: Could not find a version that satisfies the requirement carla==0.9.7 (from -r requirements.txt (line 17)) (from versions: 0.9.3, 0.9.4, 0.9.5)
ERROR: No matching distribution found for carla==0.9.7 (from -r requirements.txt (line 17))

https://pypi.org/search/?q=carla   is   carla 0.9.5

**Comment by littlemountainman** [comment]
Sorry it's not required, I will remove it from the txt
