### ISSUE TITLE
Data unreadable

### ISSUE THREAD

**Issue by Saumya-Shah** [littlemountainman/modeld#14]
I converted an mp4 video to hevc format using 

`ffmpeg -i Driving.mp4 -c:v libx265 -vtag hvc1 output.hevc`

as well as 

`ffmpeg -i Driving.mp4 -c:v libx265 -vtag hvc1 output.mp4`

But for both the files I get Data Unreadable error when running the minimal.py file. Also the sample data file mentioned in the readme is not available for download. Help please. 

Thank you.

**Comment by littlemountainman** [comment]
Yes some version of the ffmpeg versions do not convert it correctly, however you should be able to pass the mp4 directly to the model

**Comment by littlemountainman** [comment]
For that, please use main.py !

**Comment by littlemountainman** [comment]
I recommend you download the data from the readme. The link now works again

**Comment by Saumya-Shah** [comment]
Thank you very much littlemountainman!
