### ISSUE TITLE
how do you train supercombo model in keras?

### ISSUE THREAD

**Issue by banjuanshua** [littlemountainman/modeld#2]
I have a question that why supercombo.keras output points in space?  I think the lane line label is in image coordinate, is it?

**Comment by zanussbaum** [comment]
I believe that the model is just the comma.ai model from [here](https://github.com/commaai/openpilot/tree/master/models)

**Comment by littlemountainman** [comment]
Yep the model is from there, this is a minimal implementation on how to use it
